### PR TITLE
feat(search): example of scrolling and height variations of search.

### PR DESCRIPTION
**Pull request by patilkiranm**
Examples of scrolling and height variations of search.

Enhancement PR for search module: [https://github.com/fomantic/Fomantic-UI/pull/1350](https://github.com/fomantic/Fomantic-UI/pull/1350)

### CODE REVIEW

**Comment by lubber-de** [comment]
@patilkiranm Did you have time to look at my above mentioned comment? 🙂

**Comment by lubber-de** [comment]
@patilkiranm Again the question:  Did you have time to look at my [above mentioned comment](https://github.com/fomantic/Fomantic-UI-Docs/pull/199#pullrequestreview-370189909)?

**Comment by patilkiranm** [comment]
> @patilkiranm Again the question: Did you have time to look at my [above mentioned comment](https://github.com/fomantic/Fomantic-UI-Docs/pull/199#pullrequestreview-370189909)?

I will add additional description with the example.

**Comment by lubber-de** [comment]
@patilkiranm As we now merged your PR from the main repo :wink:, could you please add the additional hint you promised to make te usage more clear to the user?

**Comment by patilkiranm** [comment]
@lubber-de Hint added to scrolling and height variation

**Comment by lubber-de** [comment]
@all-contributors please add @patilkiranm for code and doc

**Comment by lubber-de** [comment]
@all-contributors please add @patilkiranm for code,doc

**Comment by lubber-de** [comment]
@all-contributors please add @patilkiranm for code

**Pull request merged**
