### PR TITLE
feat(slider): new option fireChange

### PR DESCRIPTION
**Pull request by lubber-de**
## Description
Added new option `fireChange`  as of  https://github.com/fomantic/Fomantic-UI/pull/1751

## Screenshots
image

### CODE REVIEW

**Review by ko2in — APPROVED** [review]
@lubber-de Should it contain the note that version 2.8.7 and below doesn't support the `fireChange` argument?

**Review by ko2in — APPROVED** [review]
Sorry. Forgot about my previous comment. I've read you and @exoego discussion in the PR that you explained this argument will convert the default value if it's missing. LGTM.

**Review by exoego — APPROVED** [review]
LGTM

**Review by prudho — APPROVED** [review]
LGTM

**Pull request merged**
