### PR TITLE
[Toast] Color Variants

### PR DESCRIPTION
**Pull request by lubber-de**
Examples of new Color variants as of https://github.com/fomantic/Fomantic-UI/pull/170

### CODE REVIEW

**Comment by hammy2899** [comment]
@lubber-de Could you include a screenshot of the toasts showing on the screen?

**Comment by lubber-de** [comment]
> @lubber-de Could you include a screenshot of the toasts showing on the screen?

I could, but i think it's not necessary, because the demo code already cycles through all possible colors, so the reader can instantly test it.

**Comment by hammy2899** [comment]
I mean so I can see what it looks like on the docs 😜

**Comment by ColinFrick** [comment]
The cycle doesn't seem to work for me. I only get the red color variation (the first color)

**Comment by lubber-de** [comment]
> The cycle doesn't seem to work for me. I only get the red color variation (the first color)

:thinking: ... ah, yes, because the whole example code runs all the time again (including initial set of suiIndex...) I'll find a solution

**Pull request merged**
