### PR TITLE
Misswriting on dividing header

### PR DESCRIPTION
**Pull request by josejbarneto**
In Settings tabs of Slider Module, the header title its "Calendar"

### CODE REVIEW

**Comment by hammy2899** [comment]
Thanks for the PR, can you rebase your branch to `develop` to prevent merging unnecessary commits.

**Comment by lubber-de** [comment]
@josejbarneto Kind reminder 🎗 🙂 
As @hammy2899 mentioned: Could you please rebase your PR to the current develop branch?
We would like to merge your PR, because it's a serious bug and appreciate your time you spent improving Fomantic-UI.
Thanks!

**Comment by josejbarneto** [comment]
Sorry i had the wrong mail in github so i just noticed, also im very new to git and github, i did it correctly now?

**Comment by lubber-de** [comment]
@josejbarneto Please try the following in your local repository folder:

To have your patch-branch updated (and hopefully removes every unnecessary commit, beside your fit itself) try

```console
git checkout patch-1
git rebase patch-1 develop
```
Always get the latest changes to your branches from the FUI repo before preparing a PR and branch from develop: 

```console
git remote add upstream https://github.com/fomantic/Fomantic-UI-Docs.git
git checkout develop
git pull upstream develop
git push
git checkout master
git pull upstream master
git push
```

**Comment by hammy2899** [comment]
I have rebased the branch for you 🙂

**Pull request merged**
