### PR TITLE
feat(form): set optional behavior

### PR DESCRIPTION
**Pull request by Giandrop**
## Description
Adds 'set optional' to the table of behaviors

## Related
https://github.com/fomantic/Fomantic-UI/pull/1695

### CODE REVIEW

**Review by lubber-de — DISMISSED** [review]
LGTM ( i changed the base branch to develop, we don't merge into master)

**Review by ko2in — COMMENTED** [review]
@lubber-de Shouldn't we add the info about the new option with the version number `New in 2.8.8`? So, the user can know this is only available in version 2.8.8 and above.

**Comment by lubber-de** [comment]
@ko2in Yeah, good point. @Giandrop Would you please add a label similiar to the other behaviors for 2.2.11 ?

**Review by lubber-de — APPROVED** [review]
LGTM

**Review by ColinFrick — APPROVED** [review]

**Review by ko2in — COMMENTED** [review]
LGTM.

**Pull request merged**
